modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/Arcomit/emberthral/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL="https://github.com/Arcomit/emberthral/blob/1.21.1/neoforge-update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/emberthral"
logoFile="emberthral.png"
credits="Low-Drag-MC,MCModderAnchor,Furia"
authors = "${mod_authors}"
description = '''${mod_description}'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config="${mod_id}.core.obj.mixins.json"

[[mixins]]
config="${mod_id}.core.bedrock.v1.mixins.json"

[[mixins]]
config="${mod_id}.core.filter.mixin.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
# 依赖项的类型。可以是“必需（required）”、“可选（optional）”、“不兼容（incompatible）”或“不鼓励（discouraged）”（不区分大小写）之一。
type = "required"
# 描述依赖项为何为必需或不兼容的可选字段
# reason="..."
versionRange = "${neo_version_range}"
# 依赖项的排序关系。
# BEFORE - 此 mod 在依赖项之前加载
# AFTER - 此 mod 在依赖项之后加载
ordering = "NONE"
# 此依赖项应用于 - BOTH、CLIENT 或 SERVER
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# 功能是游戏环境的特定属性，您可能想要声明您需要。
# 此示例声明您的模组需要 GL 版本 3.2 或更高版本。将添加其他功能。
# 声明这一点不会阻止您在服务器上加载您的模组。
#[features."${mod_id}"]
#openGLVersion="[3.2,)"
